'use strict';

function buildDp(P) {
    const { DP_BASE, STEUERUNG_BASE, SCHLEIFE_BASE, WETTERDATEN_SCHWELLE, TANK_ANZEIGEN,
        TANK_DP_MANUELL_PUMPE, TANK_DP_ANZEIGE_UNTEN, TANK_DP_ANZEIGE_OBEN, TANK_DP_ANZEIGE_ISTWERT,
        TANK_DP_PFAD_AUSWAHL_UNTEN, TANK_DP_PFAD_AUSWAHL_OBEN, TANK_DP_PFAD_AUSWAHL_ISTWERT,
        TANK_DP_BRUNNENPUMPE_KONFIG, TANK_DP_UNTEN_TEST, TANK_DP_OBEN_TEST,
        GARTEN_BASE, GARTEN_KONFIG, GARTEN_ANZEIGEN, NACHRICHTEN_KONFIG, NACHRICHTEN_ANZEIGEN } = P;

    return {
        status: `${STEUERUNG_BASE}.Status`,
        zeitsteuerung: `${STEUERUNG_BASE}.RegelAktiv`,
        zeitmodus: `${STEUERUNG_BASE}.Zeitmodus`,
        zsAusgeloest: `${STEUERUNG_BASE}.ZeitschaltuhrAusgeloest`,
        zsLetzteAusloesung: `${STEUERUNG_BASE}.ZeitschaltuhrLetzteAusloesung`,
        zsZeit1: `${STEUERUNG_BASE}.Zeitschaltuhr.Schaltzeit1`,
        zsZeit1Aktiv: `${STEUERUNG_BASE}.Zeitschaltuhr.Schaltzeit1Aktiv`,
        zsZeit1Astro: `${STEUERUNG_BASE}.Zeitschaltuhr.Schaltzeit1Astro`,
        zsZeit1AstroTyp: `${STEUERUNG_BASE}.Zeitschaltuhr.Schaltzeit1AstroTyp`,
        zsZeit1AstroOffset: `${STEUERUNG_BASE}.Zeitschaltuhr.Schaltzeit1AstroOffset`,
        zsZeit1Anzeige: `${STEUERUNG_BASE}.Zeitschaltuhr.Schaltzeit1Anzeige`,
        zsZeit2: `${STEUERUNG_BASE}.Zeitschaltuhr.Schaltzeit2`,
        zsZeit2Aktiv: `${STEUERUNG_BASE}.Zeitschaltuhr.Schaltzeit2Aktiv`,
        zsZeit2Astro: `${STEUERUNG_BASE}.Zeitschaltuhr.Schaltzeit2Astro`,
        zsZeit2AstroTyp: `${STEUERUNG_BASE}.Zeitschaltuhr.Schaltzeit2AstroTyp`,
        zsZeit2AstroOffset: `${STEUERUNG_BASE}.Zeitschaltuhr.Schaltzeit2AstroOffset`,
        zsZeit2Anzeige: `${STEUERUNG_BASE}.Zeitschaltuhr.Schaltzeit2Anzeige`,
        zsTagMo: `${STEUERUNG_BASE}.Zeitschaltuhr.TagMo`,
        zsTagDi: `${STEUERUNG_BASE}.Zeitschaltuhr.TagDi`,
        zsTagMi: `${STEUERUNG_BASE}.Zeitschaltuhr.TagMi`,
        zsTagDo: `${STEUERUNG_BASE}.Zeitschaltuhr.TagDo`,
        zsTagFr: `${STEUERUNG_BASE}.Zeitschaltuhr.TagFr`,
        zsTagSa: `${STEUERUNG_BASE}.Zeitschaltuhr.TagSa`,
        zsTagSo: `${STEUERUNG_BASE}.Zeitschaltuhr.TagSo`,
        schleifeAktiv: `${SCHLEIFE_BASE}.Aktiv`,
        schleifeStatus: `${SCHLEIFE_BASE}.Status`,
        schleifeLaeuft: `${SCHLEIFE_BASE}.Laeuft`,
        schleifeAktuellesVentil: `${SCHLEIFE_BASE}.AktuellesVentil`,
        schleifePauseZwischenSek: `${SCHLEIFE_BASE}.PauseZwischenSek`,
        schleifePauseZwischenHinweis: `${SCHLEIFE_BASE}.PauseZwischenSek_Hinweis`,
        schleifeGesamtzeitSek: `${SCHLEIFE_BASE}.GesamtzeitSek`,
        schleifeGesamtzeitMaxMin: `${SCHLEIFE_BASE}.GesamtzeitMaxMin`,
        schleifeBrunnenpumpePauseSek: `${SCHLEIFE_BASE}.BrunnenpumpePauseSek`,
        schleifeGesamtzeitFehler: `${SCHLEIFE_BASE}.GesamtzeitFehler`,
        schleifeGesamtzeitAnzeige: `${SCHLEIFE_BASE}.GesamtzeitAnzeige`,
        schleifeVentil1: `${SCHLEIFE_BASE}.Ventil1`,
        schleifeVentil2: `${SCHLEIFE_BASE}.Ventil2`,
        schleifeVentil3: `${SCHLEIFE_BASE}.Ventil3`,
        schleifeVentil4: `${SCHLEIFE_BASE}.Ventil4`,
        schleifeManuellStart: `${SCHLEIFE_BASE}.ManuellStart`,
        schleifeManuellStopp: `${SCHLEIFE_BASE}.ManuellStopp`,
        schleifePauseEin: `${SCHLEIFE_BASE}.PauseEin`,
        schleifePauseAus: `${SCHLEIFE_BASE}.PauseAus`,
        tankAnzStatus: `${TANK_ANZEIGEN}.Status`,
        tankManuellPumpe: TANK_DP_MANUELL_PUMPE,
        tankAnzUnten: TANK_DP_ANZEIGE_UNTEN,
        tankAnzOben: TANK_DP_ANZEIGE_OBEN,
        tankAnzIstwert: TANK_DP_ANZEIGE_ISTWERT,
        tankPfadUnten: TANK_DP_PFAD_AUSWAHL_UNTEN,
        tankPfadOben: TANK_DP_PFAD_AUSWAHL_OBEN,
        tankPfadIstwert: TANK_DP_PFAD_AUSWAHL_ISTWERT,
        tankBrunnenpumpeKonfig: TANK_DP_BRUNNENPUMPE_KONFIG,
        tankUntenTest: TANK_DP_UNTEN_TEST,
        tankObenTest: TANK_DP_OBEN_TEST,
        gartenAktiv: `${GARTEN_BASE}.Aktiv`,
        gartenPumpeAusgang: `${GARTEN_KONFIG}.GartenpumpeAusgang`,
        gartenNachtruheVon: `${GARTEN_KONFIG}.NachtruheVon`,
        gartenNachtruheBis: `${GARTEN_KONFIG}.NachtruheBis`,
        gartenNachtruheAktiv: `${GARTEN_KONFIG}.NachtruheAktiv`,
        gartenAnzNachtruhe: `${GARTEN_ANZEIGEN}.NachtruheGeradeAktiv`,
        gartenAnzPumpe: `${GARTEN_ANZEIGEN}.Gartenpumpe`,
        gartenAnzPumpeVisSteuerung: `${GARTEN_ANZEIGEN}.PumpeVisSteuerung`,
        gartenAnzStatus: `${GARTEN_ANZEIGEN}.Status`,
        nachrichtenWhatsAppAktiv: `${NACHRICHTEN_KONFIG}.WhatsApp_Aktiv`,
        nachrichtenWhatsAppInstanz: `${NACHRICHTEN_KONFIG}.WhatsApp_Instanz`,
        nachrichtenWhatsAppInstanzen: `${NACHRICHTEN_ANZEIGEN}.WhatsApp_InstanzenVerfuegbar`,
        nachrichtenTelegramAktiv: `${NACHRICHTEN_KONFIG}.Telegram_Aktiv`,
        nachrichtenTelegramInstanz: `${NACHRICHTEN_KONFIG}.Telegram_Instanz`,
        nachrichtenTelegramUser: `${NACHRICHTEN_KONFIG}.Telegram_User`,
        nachrichtenTelegramChatId: `${NACHRICHTEN_KONFIG}.Telegram_ChatId`,
        nachrichtenTelegramInstanzen: `${NACHRICHTEN_ANZEIGEN}.Telegram_InstanzenVerfuegbar`,
        nachrichtenTelegramAuthInfo: `${NACHRICHTEN_ANZEIGEN}.Telegram_AuthInfo`,
        nachrichtenEmailAktiv: `${NACHRICHTEN_KONFIG}.Email_Aktiv`,
        nachrichtenEmailAdresse: `${NACHRICHTEN_KONFIG}.Email_Adresse`,
        nachrichtenBeiManuell: `${NACHRICHTEN_KONFIG}.BeiManuell`,
        nachrichtenBeiZeit: `${NACHRICHTEN_KONFIG}.BeiZeitgesteuert`,
        nachrichtenTankstand: `${NACHRICHTEN_KONFIG}.Tankstand_InNachricht`,
        nachrichtenWhatsAppTest: `${NACHRICHTEN_KONFIG}.WhatsApp_TestSenden`,
        nachrichtenTelegramTest: `${NACHRICHTEN_KONFIG}.Telegram_TestSenden`,
        nachrichtenEmailTest: `${NACHRICHTEN_KONFIG}.Email_TestSenden`,
        nachrichtenAnzLetzte: `${NACHRICHTEN_ANZEIGEN}.LetzteNachricht`,
        nachrichtenAnzVersand: `${NACHRICHTEN_ANZEIGEN}.LetzterVersand`,
        nachrichtenAnzStatus: `${NACHRICHTEN_ANZEIGEN}.Status`,
        nachrichtenAnzTankstand: `${NACHRICHTEN_ANZEIGEN}.Tankstand_Aktuell`,
        wetterdatenSchwelleUeberschritten: `${WETTERDATEN_SCHWELLE}.Ueberschritten`,
    };
}

module.exports = { buildDp };
